# Use a imagem base do Node.js
FROM node:18.16.1-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app/gps-back

# Copie o arquivo package.json e o package-lock.json (se existir)
COPY gps-back/package*.json ./

# Instale as dependências
RUN npm install

# Copie os arquivos do backend para o contêiner
COPY gps-back/ .

# Comando padrão para iniciar o servidor
CMD ["npm", "start"]
