# Use a imagem base do Node.js
FROM node:18.16.1-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app/gps-back

# Copie o arquivo package.json e o package-lock.json (se existir)
COPY . .

# Instale as dependências
RUN npm install

# Comando padrão para iniciar o servidor
CMD ["npm", "start"]
