# Use a imagem base do Node.js
FROM node:18.16.1-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app/gps-front

# Copie o arquivo package.json e o package-lock.json (se existir)
COPY gps-front/package*.json ./

# Instale as dependências
RUN npm install

# Copie os arquivos do frontend para o contêiner
COPY gps-front/ .

# Comando padrão para iniciar o aplicativo rode o comando npm run dev
CMD ["npm", "run", "dev"]